# Generated by Django 5.1.1 on 2024-09-18 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_date_joined_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(choices=[('heart_rate', 'Heart Beats Per Minute'), ('hours_slept', 'Hours Sleeping'), ('water_intake', 'Water Liters'), ('calories', 'Kilo Calories'), ('weight', 'Weight (kg)'), ('temperature', 'Temperature (Celsius)')], max_length=20)),
                ('value', models.FloatField()),
                ('measurement_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
